version: 2.0.0.{build}

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal