version: 2.0.0.{build}

install:
    - rd /s /q C:\Tools\nuget
    - md C:\Tools\nuget
    - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', 'C:\Tools\nuget\nuget.exe')

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal