version: 2.0.0.{build}

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
- cmd: nuget restore

after_build:
- ps : .\Create-NugetPackages.ps1
- ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }